apiVersion: apps/v1
kind: Deployment
metadata:
  name: project04-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project04
  template:
    metadata:
      labels:
        app: project04
    spec:
      containers:
        - name: project04
          image: fajouianas/devops-with-kubernetes:1.06
